/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Event {
  'flagEvent' : [] | [FlagEvent],
  'description' : string,
  'timestamp' : Time,
  'eventType' : EventType,
}
export type EventType = { 'flag' : null } |
  { 'point' : null };
export interface FlagEvent {
  'team' : string,
  'timestamp' : Time,
  'reason' : string,
}
export interface Scoreboard {
  'team1Score' : bigint,
  'team2Icon' : TeamIcon,
  'team2Role' : TeamRole,
  'team2Score' : bigint,
  'team1Icon' : TeamIcon,
  'team1Role' : TeamRole,
}
export type TeamIcon = { 'dolphin' : null } |
  { 'tornado' : null } |
  { 'fist' : null } |
  { 'bullfrog' : null };
export type TeamRole = { 'none' : null } |
  { 'defense' : null } |
  { 'offense' : null };
export type Time = bigint;
export interface _SERVICE {
  'addEvent' : ActorMethod<[string, string, EventType], undefined>,
  'addFlagEvent' : ActorMethod<[string, string, string], undefined>,
  'endSession' : ActorMethod<[string], undefined>,
  'getEvents' : ActorMethod<[string], Array<Event>>,
  'getScoreboard' : ActorMethod<[string], Scoreboard>,
  'getSessionMetadata' : ActorMethod<[string], [string, Time, [] | [Time]]>,
  'isValidSessionCode' : ActorMethod<[string], boolean>,
  'setTeamIcons' : ActorMethod<[string, TeamIcon, TeamIcon], undefined>,
  'startSession' : ActorMethod<[string, string], undefined>,
  'updateScoreboard' : ActorMethod<
    [string, bigint, bigint, TeamRole, TeamRole],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];