/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EventType = IDL.Variant({ 'flag' : IDL.Null, 'point' : IDL.Null });
export const Time = IDL.Int;
export const FlagEvent = IDL.Record({
  'team' : IDL.Text,
  'timestamp' : Time,
  'reason' : IDL.Text,
});
export const Event = IDL.Record({
  'flagEvent' : IDL.Opt(FlagEvent),
  'description' : IDL.Text,
  'timestamp' : Time,
  'eventType' : EventType,
});
export const TeamIcon = IDL.Variant({
  'dolphin' : IDL.Null,
  'tornado' : IDL.Null,
  'fist' : IDL.Null,
  'bullfrog' : IDL.Null,
});
export const Scoreboard = IDL.Record({
  'team1Score' : IDL.Nat,
  'team2Icon' : TeamIcon,
  'team2Score' : IDL.Nat,
  'team1Icon' : TeamIcon,
});

export const idlService = IDL.Service({
  'addEvent' : IDL.Func([IDL.Text, IDL.Text, EventType], [], []),
  'addFlagEvent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'clearFlagOverlays' : IDL.Func([IDL.Text], [], []),
  'endSession' : IDL.Func([IDL.Text], [], []),
  'getActiveFlagOverlays' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FlagEvent)],
      ['query'],
    ),
  'getEvents' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
  'getScoreboard' : IDL.Func([IDL.Text], [Scoreboard], ['query']),
  'getSessionMetadata' : IDL.Func(
      [IDL.Text],
      [IDL.Text, Time, IDL.Opt(Time)],
      ['query'],
    ),
  'isValidSessionCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'startSession' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateScoreboard' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, TeamIcon, TeamIcon],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EventType = IDL.Variant({ 'flag' : IDL.Null, 'point' : IDL.Null });
  const Time = IDL.Int;
  const FlagEvent = IDL.Record({
    'team' : IDL.Text,
    'timestamp' : Time,
    'reason' : IDL.Text,
  });
  const Event = IDL.Record({
    'flagEvent' : IDL.Opt(FlagEvent),
    'description' : IDL.Text,
    'timestamp' : Time,
    'eventType' : EventType,
  });
  const TeamIcon = IDL.Variant({
    'dolphin' : IDL.Null,
    'tornado' : IDL.Null,
    'fist' : IDL.Null,
    'bullfrog' : IDL.Null,
  });
  const Scoreboard = IDL.Record({
    'team1Score' : IDL.Nat,
    'team2Icon' : TeamIcon,
    'team2Score' : IDL.Nat,
    'team1Icon' : TeamIcon,
  });
  
  return IDL.Service({
    'addEvent' : IDL.Func([IDL.Text, IDL.Text, EventType], [], []),
    'addFlagEvent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'clearFlagOverlays' : IDL.Func([IDL.Text], [], []),
    'endSession' : IDL.Func([IDL.Text], [], []),
    'getActiveFlagOverlays' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FlagEvent)],
        ['query'],
      ),
    'getEvents' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
    'getScoreboard' : IDL.Func([IDL.Text], [Scoreboard], ['query']),
    'getSessionMetadata' : IDL.Func(
        [IDL.Text],
        [IDL.Text, Time, IDL.Opt(Time)],
        ['query'],
      ),
    'isValidSessionCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'startSession' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateScoreboard' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, TeamIcon, TeamIcon],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };