/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Scoreboard {
    team1Score: bigint;
    team2Icon: TeamIcon;
    team2Role: TeamRole;
    team2Score: bigint;
    team1Icon: TeamIcon;
    team1Role: TeamRole;
}
export interface Event {
    flagEvent?: FlagEvent;
    description: string;
    timestamp: Time;
    eventType: EventType;
}
export interface FlagEvent {
    team: string;
    timestamp: Time;
    reason: string;
}
export enum EventType {
    flag = "flag",
    point = "point"
}
export enum TeamIcon {
    dolphin = "dolphin",
    tornado = "tornado",
    fist = "fist",
    bullfrog = "bullfrog"
}
export enum TeamRole {
    none = "none",
    defense = "defense",
    offense = "offense"
}
export interface backendInterface {
    addEvent(sessionCode: string, description: string, eventType: EventType): Promise<void>;
    addFlagEvent(sessionCode: string, team: string, reason: string): Promise<void>;
    endSession(sessionCode: string): Promise<void>;
    getEvents(sessionCode: string): Promise<Array<Event>>;
    getScoreboard(sessionCode: string): Promise<Scoreboard>;
    getSessionMetadata(sessionCode: string): Promise<[string, Time, Time | null]>;
    isValidSessionCode(sessionCode: string): Promise<boolean>;
    setTeamIcons(sessionCode: string, team1Icon: TeamIcon, team2Icon: TeamIcon): Promise<void>;
    startSession(broadcaster: string, sessionCode: string): Promise<void>;
    updateScoreboard(sessionCode: string, team1Score: bigint, team2Score: bigint, team1Role: TeamRole, team2Role: TeamRole): Promise<void>;
}
import type { Event as _Event, EventType as _EventType, FlagEvent as _FlagEvent, Scoreboard as _Scoreboard, TeamIcon as _TeamIcon, TeamRole as _TeamRole, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addEvent(arg0: string, arg1: string, arg2: EventType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEvent(arg0, arg1, to_candid_EventType_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEvent(arg0, arg1, to_candid_EventType_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addFlagEvent(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFlagEvent(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFlagEvent(arg0, arg1, arg2);
            return result;
        }
    }
    async endSession(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.endSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endSession(arg0);
            return result;
        }
    }
    async getEvents(arg0: string): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvents(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvents(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScoreboard(arg0: string): Promise<Scoreboard> {
        if (this.processError) {
            try {
                const result = await this.actor.getScoreboard(arg0);
                return from_candid_Scoreboard_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScoreboard(arg0);
            return from_candid_Scoreboard_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionMetadata(arg0: string): Promise<[string, Time, Time | null]> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionMetadata(arg0);
                return [
                    result[0],
                    result[1],
                    from_candid_opt_n15(this._uploadFile, this._downloadFile, result[2])
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionMetadata(arg0);
            return [
                result[0],
                result[1],
                from_candid_opt_n15(this._uploadFile, this._downloadFile, result[2])
            ];
        }
    }
    async isValidSessionCode(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isValidSessionCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isValidSessionCode(arg0);
            return result;
        }
    }
    async setTeamIcons(arg0: string, arg1: TeamIcon, arg2: TeamIcon): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTeamIcons(arg0, to_candid_TeamIcon_n16(this._uploadFile, this._downloadFile, arg1), to_candid_TeamIcon_n16(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTeamIcons(arg0, to_candid_TeamIcon_n16(this._uploadFile, this._downloadFile, arg1), to_candid_TeamIcon_n16(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async startSession(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startSession(arg0, arg1);
            return result;
        }
    }
    async updateScoreboard(arg0: string, arg1: bigint, arg2: bigint, arg3: TeamRole, arg4: TeamRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateScoreboard(arg0, arg1, arg2, to_candid_TeamRole_n18(this._uploadFile, this._downloadFile, arg3), to_candid_TeamRole_n18(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateScoreboard(arg0, arg1, arg2, to_candid_TeamRole_n18(this._uploadFile, this._downloadFile, arg3), to_candid_TeamRole_n18(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
}
function from_candid_EventType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventType): EventType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Event_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Event {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Scoreboard_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Scoreboard): Scoreboard {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_TeamIcon_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeamIcon): TeamIcon {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_TeamRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeamRole): TeamRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FlagEvent]): FlagEvent | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    team1Score: bigint;
    team2Icon: _TeamIcon;
    team2Role: _TeamRole;
    team2Score: bigint;
    team1Icon: _TeamIcon;
    team1Role: _TeamRole;
}): {
    team1Score: bigint;
    team2Icon: TeamIcon;
    team2Role: TeamRole;
    team2Score: bigint;
    team1Icon: TeamIcon;
    team1Role: TeamRole;
} {
    return {
        team1Score: value.team1Score,
        team2Icon: from_candid_TeamIcon_n11(_uploadFile, _downloadFile, value.team2Icon),
        team2Role: from_candid_TeamRole_n13(_uploadFile, _downloadFile, value.team2Role),
        team2Score: value.team2Score,
        team1Icon: from_candid_TeamIcon_n11(_uploadFile, _downloadFile, value.team1Icon),
        team1Role: from_candid_TeamRole_n13(_uploadFile, _downloadFile, value.team1Role)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    flagEvent: [] | [_FlagEvent];
    description: string;
    timestamp: _Time;
    eventType: _EventType;
}): {
    flagEvent?: FlagEvent;
    description: string;
    timestamp: Time;
    eventType: EventType;
} {
    return {
        flagEvent: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.flagEvent)),
        description: value.description,
        timestamp: value.timestamp,
        eventType: from_candid_EventType_n7(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dolphin: null;
} | {
    tornado: null;
} | {
    fist: null;
} | {
    bullfrog: null;
}): TeamIcon {
    return "dolphin" in value ? TeamIcon.dolphin : "tornado" in value ? TeamIcon.tornado : "fist" in value ? TeamIcon.fist : "bullfrog" in value ? TeamIcon.bullfrog : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    none: null;
} | {
    defense: null;
} | {
    offense: null;
}): TeamRole {
    return "none" in value ? TeamRole.none : "defense" in value ? TeamRole.defense : "offense" in value ? TeamRole.offense : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    flag: null;
} | {
    point: null;
}): EventType {
    return "flag" in value ? EventType.flag : "point" in value ? EventType.point : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Array<Event> {
    return value.map((x)=>from_candid_Event_n4(_uploadFile, _downloadFile, x));
}
function to_candid_EventType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): _EventType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TeamIcon_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeamIcon): _TeamIcon {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_TeamRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeamRole): _TeamRole {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeamIcon): {
    dolphin: null;
} | {
    tornado: null;
} | {
    fist: null;
} | {
    bullfrog: null;
} {
    return value == TeamIcon.dolphin ? {
        dolphin: null
    } : value == TeamIcon.tornado ? {
        tornado: null
    } : value == TeamIcon.fist ? {
        fist: null
    } : value == TeamIcon.bullfrog ? {
        bullfrog: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeamRole): {
    none: null;
} | {
    defense: null;
} | {
    offense: null;
} {
    return value == TeamRole.none ? {
        none: null
    } : value == TeamRole.defense ? {
        defense: null
    } : value == TeamRole.offense ? {
        offense: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): {
    flag: null;
} | {
    point: null;
} {
    return value == EventType.flag ? {
        flag: null
    } : value == EventType.point ? {
        point: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
